// Azerbaijan districts (rayons) - all 78 cities/districts
export const AZERBAIJAN_CITIES = [
  'Abşeron',
  'Ağcabədi',
  'Ağdam',
  'Ağdaş',
  'Ağdərə',
  'Ağstafa',
  'Ağsu',
  'Astara',
  'Babək',
  'Bakı',
  'Balakən',
  'Beyləqan',
  'Bərdə',
  'Biləsuvar',
  'Cəbrayıl',
  'Cəlilabad',
  'Culfa',
  'Daşkəsən',
  'Dəliməmmədli',
  'Füzuli',
  'Gədəbəy',
  'Gəncə',
  'Goranboy',
  'Göyçay',
  'Göygöl',
  'Göytəpə',
  'Hacıqabul',
  'Horadiz',
  'Xaçmaz',
  'Xankəndi',
  'Xızı',
  'Xırdalan',
  'Xocalı',
  'Xocavənd',
  'Xudat',
  'İmişli',
  'İsmayıllı',
  'Kəlbəcər',
  'Kürdəmir',
  'Qax',
  'Qazax',
  'Qəbələ',
  'Qobustan',
  'Qovlar',
  'Quba',
  'Qubadlı',
  'Qusar',
  'Laçın',
  'Lerik',
  'Lənkəran',
  'Liman',
  'Masallı',
  'Mingəçevir',
  'Naftalan',
  'Naxçıvan',
  'Neftçala',
  'Oğuz',
  'Ordubad',
  'Saatlı',
  'Sabirabad',
  'Salyan',
  'Samux',
  'Siyəzən',
  'Sumqayıt',
  'Şabran',
  'Şahbuz',
  'Şamaxı',
  'Şəki',
  'Şəmkir',
  'Şərur',
  'Şirvan',
  'Şuşa',
  'Tərtər',
  'Tovuz',
  'Ucar',
  'Yardımlı',
  'Yevlax',
  'Zaqatala',
  'Zəngilan',
  'Zərdab'
] as const;

export const BOARD_TYPES = [
  { value: 'billboard', label: '🔶 Bilbord', description: 'Böyük ölçülü reklam lövhəsi' },
  { value: 'digital', label: '📺 Rəqəmsal Ekran', description: 'LED/LCD ekranlı reklam' },
  { value: 'poster', label: '📋 Poster Lövhəsi', description: 'Orta ölçülü poster' },
  { value: 'wallscape', label: '🏢 Divar Lövhəsi', description: 'Bina divarında reklam' },
  { value: 'transit', label: '🚌 Nəqliyyat Reklamı', description: 'Avtobus, metro reklamı' },
  { value: 'street', label: '🚏 Küçə Lövhəsi', description: 'Küçə səviyyəsində reklam' },
  { value: 'bridge', label: '🌉 Körpü Lövhəsi', description: 'Körpü üzərində reklam' },
  { value: 'roof', label: '🏠 Dam Lövhəsi', description: 'Bina damında reklam' }
] as const;

// Get all cities as array
export const getAllCities = (): string[] => {
  return [...AZERBAIJAN_CITIES];
};

// Default coordinates for Azerbaijan (Baku center)
export const AZERBAIJAN_DEFAULT_COORDS = {
  lat: 40.4093,
  lng: 49.8671,
  zoom: 12
};

// Major city coordinates for quick selection
export const CITY_COORDINATES: Record<string, { lat: number; lng: number }> = {
  'Bakı': { lat: 40.4093, lng: 49.8671 },
  'Gəncə': { lat: 40.6828, lng: 46.3606 },
  'Sumqayıt': { lat: 40.5897, lng: 49.6686 },
  'Mingəçevir': { lat: 40.7697, lng: 47.0461 },
  'Şirvan': { lat: 39.9367, lng: 48.9289 },
  'Naxçıvan': { lat: 39.2089, lng: 45.4125 },
  'Lənkəran': { lat: 38.7542, lng: 48.8511 },
  'Quba': { lat: 41.3617, lng: 48.5133 },
  'Şəki': { lat: 41.1919, lng: 47.1706 },
  'Yevlax': { lat: 40.6178, lng: 47.1506 },
  'Xaçmaz': { lat: 41.4617, lng: 48.8056 },
  'Qazax': { lat: 41.0925, lng: 45.3658 },
  'Şamaxı': { lat: 40.6317, lng: 48.6417 }
};
